In [1]:
import pandas as pd

In [2]:
log_book = pd.read_excel('Glider Log Book.xlsx')
log_book

,Date,Flight Number,Type of Glider,License Number,Launch Method A/G/L,Release Altitude,Max Altitude,Location,Flight Training Received,Solo,Pilot in Command,Remarks,Instructor
0,2019-07-06,1,SGS-233A,N17903,A,3700,6700,4NY8,0.8,NaN,NaN,"Intro flight, thermalling, speed control, turn...",Evan H.
1,2019-07-07,2,SGS-233A,N65833,A,3700,3700,4NY8,0.3,NaN,NaN,"Turns, turn coordination, intro to pattern and...",Evan H.
2,2019-07-07,3,SGS-233A,N65833,A,3700,3700,4NY8,0.3,NaN,NaN,"Stalls, turning stalls, S wind landing, and as...",Evan H.
3,2019-07-09,4,SGS-233A,N65833,A,3700,3700,4NY8,0.3,NaN,NaN,"T/O demo, tow demo, turns coordination",Evan H.
4,2019-07-09,5,SGS-233A,N65833,A,3700,3700,4NY8,0.3,NaN,NaN,"Assisted tow, coordination looking good! Assis...",Evan H.
...,...,...,...,...,...,...,...,...,...,...,...,...,...
60,2019-10-25,61,SGS-233A,N17903,A,2700,2700,4NY8,NaN,0.1,0.1,Even better,NaN
61,2019-10-31,62,SGS-233A,N17903,A,3700,3700,4NY8,NaN,0.5,0.5,Landed short,NaN
62,2019-11-06,63,SGS-233A,N17903,A,3700,4500,4NY8,NaN,0.5,0.5,Good flight :),NaN
63,2019-11-07,64,SGS-233A,N17903,A,3700,3700,4NY8,NaN,0.4,0.4,NaN,NaN
64,2019-11-07,65,SGS-233A,N17903,A,3700,3700,4NY8,NaN,0.4,0.4,NaN,NaN

In [3]:
start_date = log_book.Date[1]
start_date

Timestamp('2019-07-07 00:00:00')

In [4]:
first_solo_record = log_book.loc[log_book['Solo'].first_valid_index()]
first_solo_date = first_solo_record.Date
first_solo_date

Timestamp('2019-08-13 00:00:00')

In [5]:
delta = first_solo_date - start_date
print(delta.days, 'days to solo')

37 days to solo

#### Not bad, consistency is key, which is what I'll look at next.